// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WdhSVfyEYnextDzQgbzVw
// Component: LrMlJbA51Lb0
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { AntdMenu } from "@plasmicpkgs/antd5/skinny/registerMenu"; // plasmic-import: fo-n3xHvdqt/codeComponent
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu"; // plasmic-import: QSmezaW-Gyu/codeComponent
import { useScreenVariants as useScreenVariants_9MfIAg66EL9T } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9mfIAg66eL9T/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_applicant_tracking_system.module.css"; // plasmic-import: 4WdhSVfyEYnextDzQgbzVw/projectcss
import sty from "./PlasmicNavigation.module.css"; // plasmic-import: LrMlJbA51Lb0/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: CgBqLcymFBCF/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: YMj6hslVtZDL/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: nEg9FfIgp9AM/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: j1_vJR3Z6Let/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: X5cuTmL4JeiK/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: Fj3_pwaAADQ8/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: wK3DMlMfzzVn/icon

createPlasmicElementProxy;

export const PlasmicNavigation__VariantProps = new Array();

export const PlasmicNavigation__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavigation__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_9MfIAg66EL9T()
  });
  return (
    <AntdMenu
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
      expandIcon={null}
      mode={
        hasVariant(globalVariants, "screen", "mobileOnly")
          ? "horizontal"
          : undefined
      }
    >
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__oKkSn)}
        key={"menuItemKey0"}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__mNbDu
          )}
        >
          {"StarterKit"}
        </div>
      </AntdMenuItem>
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__cTta6)}
        key={"menuItemKey1"}
        onClick={async () => {
          const $steps = {};
          $steps["goToHomepage"] = true
            ? (() => {
                const actionArgs = {};
                return (({ destination }) => {
                  __nextRouter?.push(destination);
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            typeof $steps["goToHomepage"] === "object" &&
            typeof $steps["goToHomepage"].then === "function"
          ) {
            $steps["goToHomepage"] = await $steps["goToHomepage"];
          }
        }}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__miWgp)}
        >
          <IconIcon
            className={classNames(projectcss.all, sty.svg__soApp)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__psiZf
            )}
          >
            {"Dashboard"}
          </div>
        </p.Stack>
      </AntdMenuItem>
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__nvE5)}
        key={"menuItemKey2"}
        onClick={async () => {
          const $steps = {};
          $steps["goToJobPostings"] = true
            ? (() => {
                const actionArgs = {};
                return (({ destination }) => {
                  __nextRouter?.push(destination);
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            typeof $steps["goToJobPostings"] === "object" &&
            typeof $steps["goToJobPostings"].then === "function"
          ) {
            $steps["goToJobPostings"] = await $steps["goToJobPostings"];
          }
        }}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__l4YJ)}
        >
          <Icon2Icon
            className={classNames(projectcss.all, sty.svg__qAo9B)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__rnNrg
            )}
          >
            {"Job Postings"}
          </div>
        </p.Stack>
      </AntdMenuItem>
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__lXQhD)}
        key={"menuItemKey3"}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__pNmcX)}
        >
          <Icon3Icon
            className={classNames(projectcss.all, sty.svg__rWfOm)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__qYcU8
            )}
          >
            {"Candidate Pipeline"}
          </div>
        </p.Stack>
      </AntdMenuItem>
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__rsDdo)}
        key={"menuItemKey4"}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__zwN0H)}
        >
          <Icon4Icon
            className={classNames(projectcss.all, sty.svg__oXva2)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cthmb
            )}
          >
            {"Interview Scheduling"}
          </div>
        </p.Stack>
      </AntdMenuItem>
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__asiih)}
        key={"menuItemKey5"}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__mPkNe)}
        >
          <Icon5Icon
            className={classNames(projectcss.all, sty.svg__bBoOj)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__bxFzk
            )}
          >
            {"Reports"}
          </div>
        </p.Stack>
      </AntdMenuItem>
      <div className={classNames(projectcss.all, sty.freeBox__uVR)} />
      {(() => {
        try {
          return !currentUser.isLoggedIn;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <AntdMenuItem
          className={classNames("__wab_instance", sty.menuItem__aF5Ev)}
          key={"menuItemKey6"}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__ybIjq)}
          >
            <Icon6Icon
              className={classNames(projectcss.all, sty.svg__qaFGv)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___0IipX
              )}
            >
              {"Log in"}
            </div>
          </p.Stack>
        </AntdMenuItem>
      ) : null}
      {(() => {
        try {
          return currentUser.isLoggedIn;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <AntdMenuItem
          className={classNames("__wab_instance", sty.menuItem__tBpGs)}
          key={"menuItemKey7"}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___8H7T8)}
          >
            <Icon6Icon
              className={classNames(projectcss.all, sty.svg__cvg0)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mxMqS
              )}
            >
              {"Log out"}
            </div>
          </p.Stack>
        </AntdMenuItem>
      ) : null}
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__duLvS)}
        key={"menuItemKey8"}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___1Nib5)}
        >
          <Icon6Icon
            className={classNames(projectcss.all, sty.svg__uftYd)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__bpe4G
            )}
          >
            {"Messages"}
          </div>
        </p.Stack>
      </AntdMenuItem>
      <AntdMenuItem
        className={classNames("__wab_instance", sty.menuItem__vNton)}
        key={"menuItemKey9"}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__iwIu7)}
        >
          <Icon7Icon
            className={classNames(projectcss.all, sty.svg__avFu2)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___7FtW
            )}
          >
            {"Settings"}
          </div>
        </p.Stack>
      </AntdMenuItem>
    </AntdMenu>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNavigation__ArgProps,
          internalVariantPropNames: PlasmicNavigation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavigation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavigation";
  } else {
    func.displayName = `PlasmicNavigation.${nodeName}`;
  }
  return func;
}

export const PlasmicNavigation = Object.assign(
  // Top-level PlasmicNavigation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicNavigation
    internalVariantProps: PlasmicNavigation__VariantProps,
    internalArgProps: PlasmicNavigation__ArgProps
  }
);

export default PlasmicNavigation;
/* prettier-ignore-end */
